services:
  web:
    build: .
    container_name: berea
    image: berea
    expose:
      - 8000
  
  nginx:
    build: ./nginx
    container_name: berea-nginx
    image: berea-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
