services:
  wsgi:
    build: .
    container_name: berea-wsgi
    image: berea-wsgi
    volumes:
      - ./static:/app/static
    expose:
      - 8000
  
  nginx:
    build: ./nginx
    container_name: berea-nginx
    image: berea-nginx
    volumes:
      - ./static:/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wsgi
